name: electronics_erp
description: "Mobile app for Electronics ERP System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  logger: ^2.6.2
  fl_chart: ^0.65.0
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
